# Generated by Django 5.2.7 on 2026-01-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modreg', '0002_module_delete_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='urgent',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='room',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='details',
            new_name='courses_registered',
        ),
        migrations.RemoveField(
            model_name='module',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='module',
            name='type',
        ),
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='credit',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
