# Generated by Django 5.2.7 on 2026-01-21 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('modreg', '0004_remove_module_courses_registered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='courses_registered',
        ),
        migrations.AddField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(related_name='modules', to='auth.group'),
        ),
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='registered_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
