# Generated by Django 5.2.7 on 2026-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('modreg', '0005_remove_module_courses_registered_module_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='courses',
        ),
        migrations.AddField(
            model_name='module',
            name='courses_registered',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
