# Generated by Django 5.2.7 on 2026-01-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modreg', '0006_remove_module_courses_module_courses_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
